import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:prototype/Utilis/toastMessage.dart';
import 'package:prototype/data/network/network_service_api.dart';
import 'package:prototype/resources/constants/endpoints.dart';
import 'package:prototype/resources/constants/userInfo.dart';
import 'package:prototype/view/auth/login/loginView.dart';
import 'package:prototype/view/bottomNav/bottomNav.dart';
import 'package:prototype/view_model/sharedPreference/sharedPreference.dart';

class LoginController extends GetxController {
  final TextEditingController emailController = TextEditingController();
  final TextEditingController passwordController = TextEditingController();
  static final _googleSignIn = GoogleSignIn();

  /// Handles user login via API
  Future<void> userLoginWithApi() async {
    var data = {
      "email": emailController.text.trim(),
      "password": passwordController.text.trim(),
    };

    try {
      final response =
          await NetworkServiceApi().postData(EndPoints.userLogin, data);

      if (response["status"] == 200) {
        ToastMessage.show("User login successful");

        // save data in the local cache
        await AllLocalData().setUserId(response['data']["user"]["user_id"]);
        await AllLocalData().setEmail(response['data']["user"]["email"]);
        await AllLocalData().setUsername(
            "${response['data']["user"]["first_name"]} ${response['data']["user"]["last_name"]}");
        await AllLocalData().setIsLoggedIn(true);

        // navigate to home screen
        Get.to(() => BottomNB());
      } else {
        ToastMessage.show(
            "Login Failed: ${response['message'] ?? 'Unknown error'}");
      }
    } catch (e) {
      ToastMessage.show("An error occurred during login");
      print("Login Error: $e");
    }
  }

  // Log out the user
  Future<void> logoutUser() async {
    try {
      // Clear all shared preferences data
      await AllLocalData().clearAll();

      // Provide feedback to the user (e.g., Snackbar message)
      ToastMessage.show("You have successfully logged out.");

      // Navigate to LoginView, clearing navigation history
      Get.offAll(() => LoginView());
    } catch (e) {
      // Handle potential errors
      ToastMessage.show("An error occurred while logging out.");
    }
  }

  /// Handles Google sign-in
  Future<void> signInWithGoogle() async {
    final user = await _googleSignIn.signIn();
    if (user == null) {
      print("Google sign-in was cancelled");
      return;
    }

    try {
      var data = {
        "first_name": user.displayName?.split(" ")[0] ?? "",
        "last_name": user.displayName?.split(" ").sublist(1).join(" ") ?? "",
        "email": user.email,
        "phone_number": "",
        "password": "AutoGeneratedPass#2025",
        "date_of_birth": "",
        "profile_picture_url": user.photoUrl ?? "",
        "country": "",
        "address": ""
      };

      final response = await NetworkServiceApi()
          .postData(EndPoints.userDetailsRegister, data);
      print("Google Sign-In Response: $response");

      userDetails.userName = user.displayName ?? "Unknown";
    } catch (err) {
      print("Error during Google sign-in: $err");
    }
  }

  /// Handles Google sign-out
  Future<void> signOutWithGoogle() async {
    try {
      await _googleSignIn.signOut();
      emailController.clear();
      passwordController.clear();
      Get.snackbar("Success", "Logged out successfully",
          snackPosition: SnackPosition.BOTTOM);
      Get.offAll(() => LoginView());
    } catch (e) {
      print("Error signing out: $e");
      Get.snackbar("Error", "Failed to sign out",
          snackPosition: SnackPosition.BOTTOM);
    }
  }
}
